openlookeng/hetu-core

presto-hive/src/main/java/io/prestosql/plugin/hive/HiveCoercionPolicy.java, presto-orc/src/main/java/io/prestosql/orc/reader/AbstractNumericColumnReader.java, presto-orc/src/main/java/io/prestosql/orc/reader/ColumnReaders.java, presto-orc/src/main/java/io/prestosql/orc/reader/SliceColumnReader.java, presto-orc/src/test/java/io/prestosql/orc/TestAbstractNumbericColumnReader.java, presto-spi/src/main/java/io/prestosql/spi/block/IntArrayBlock.java, presto-spi/src/main/java/io/prestosql/spi/type/AbstractType.java, presto-spi/src/main/java/io/prestosql/spi/type/VarcharType.java
kind bug
Fixes #I44SI7 #I3PSDU
=> [I44SI7] [I3PSDU] Fix Alter Column DataType Issue

presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/JdbcUpdatablePageSource.java
=> static field correction

hetu-heuristic-index/src/test/java/io/hetu/core/plugin/heuristicindex/index/btree/TestSnappyCompressionSerializer.java
/kind bug 
fixed spot bug for TestSnappyCompressionSerializer.java
Fixes #196
=> Fixed Spotbug reported issue DLS-DEAD_LOCAL_STORE

hetu-heuristic-index/src/main/java/io/hetu/core/plugin/heuristicindex/index/btree/SnappyCompressionSerializer.java
=> remove the unused variable

hetu-heuristic-index/src/test/java/io/hetu/core/heuristicindex/TestIndexResources.java
/kind bug
spotbug fixes for TestIndexResources.java
Fixes #197
=> spotbug fixes for TestIndexResources.java

hetu-heuristic-index/src/main/java/io/hetu/core/plugin/heuristicindex/index/bloom/BloomIndex.java
=> [177]:"fix for spotbug in bloomindex"

hetu-heuristic-index/src/test/java/io/hetu/core/heuristicindex/TestPartitionIndexWriter.java
/kind bug 
spot bug fixed for test participation index.java
Fixes #195
=> spot bug fixed for test participation index

hetu-carbondata/src/main/java/io/hetu/core/plugin/carbondata/CarbondataHetuFilterUtil.java
=> use stringbuilder concatenation

hetu-carbondata/src/test/java/io/hetu/core/plugin/carbondata/integrationtest/TestCarbondataAutoCleanup.java
=> dead local store fix

hetu-hbase/src/test/java/io/hetu/core/plugin/hbase/metadata/TestingHBaseTableUtils.java
=> [175]: Fix for spot bug

hetu-carbondata/src/main/java/io/hetu/core/plugin/carbondata/CarbondataHetuOutputFormat.java
=> removing dead variable

hetu-heuristic-index/src/test/java/io/hetu/core/plugin/heuristicindex/index/btree/TestBTreeIndex.java
/kind bug
spotbug fix for TestBTreeIndex
Fixes #193
=> spotbug fix for TestBTreeIndex

presto-hive/src/test/java/io/prestosql/plugin/hive/TestHiveFileFormats.java
=> [177]: fix spot bug issue in TestHiveFileFormats

hetu-carbondata/src/test/java/io/hetu/core/plugin/carbondata/integrationtest/TestCarbonAutoVacuum.java
=> added assert to ensure catalog is not null

presto-hive/src/main/java/io/prestosql/plugin/hive/orc/OrcSelectivePageSourceFactory.java
=> [177]: Fix spot bug issue in OrcSelectivePageSourceFactory

presto-main/src/main/java/io/prestosql/Session.java, presto-main/src/main/java/io/prestosql/SystemSessionProperties.java, presto-main/src/main/java/io/prestosql/operator/scalar/DateTimeFunctions.java, presto-main/src/main/java/io/prestosql/type/TimestampOperators.java, presto-main/src/test/java/io/prestosql/operator/scalar/TestDateTimeFunctions.java, presto-spi/src/main/java/io/prestosql/spi/session/PropertyMetadata.java
/kind bug
Fixes bug in `to_unixtime` function.
Fixes #171 
Added session property `time_zone_id`.
=> [171] Fix for to_unixtime() issue

hetu-hive-functions/src/test/java/io/hetu/core/hive/dynamicfunctions/TestFunctionMetadata.java
Fix spot bug issue.
Fixes #177
=> [#177] Fix: spotbug issue TestFunctionMetadata

presto-hive/src/main/java/io/prestosql/plugin/hive/orc/OrcPageSource.java
Fix for spot bug
/kind bug 
removed dead variables
Fixes #177
=> [177]: Fix for spot bug OrcPageSource

presto-base-jdbc/src/test/java/io/prestosql/plugin/splitmanager/TestStepCalcManage.java
/kind bug
Making use of return value.
Fixes #210
=> return value ignored no side effect fix

presto-base-jdbc/src/test/java/io/prestosql/plugin/jdbc/MockConnection.java
/kind bug
Non null return violation fix
Fixes #211
=> Non null return violation fix

hetu-carbondata/src/test/java/io/hetu/core/plugin/carbondata/server/HetuTestServer.java
/kind bug 
Fixed resource leakage reported by Spotbug for HetuTestServer.
Fixes #183
=> [183] handled resource leakage for ResultSet object.

hetu-hbase/src/test/java/io/hetu/core/plugin/hbase/TestHBase.java
/kind bug 
spot bug fix for TestHetuServer
Fixes #177
=> Spotbug fix for TestHbase file

hetu-hbase/src/test/java/io/hetu/core/plugin/hbase/client/TestResult.java
/kind bug
Spotbug fix for TestResults.java file
Fixes #177
=> [177] Spotbugs fix for TestResult file

presto-base-jdbc/src/main/java/io/prestosql/sql/builder/functioncall/FunctionWriterManager.java
/kind bug
Spotbug fix for FunctionWriterManager
Fixes #177
=> SpotBug fix for FunctionWriterManager

presto-memory/src/test/java/io/prestosql/plugin/memory/TestMemorySelection.java
/kind bug 
Removed Dead Local Store Variable from TestMemorySelection
Fixes #243
=> [243] Dead Local Store Issue

presto-hive/src/main/java/io/prestosql/plugin/hive/orc/OrcPageSourceFactory.java, presto-hive/src/test/java/io/prestosql/plugin/hive/TestHiveIntegrationSmokeTest.java, presto-tests/src/main/java/io/prestosql/tests/TestingPrestoClient.java
kind bug 
Fixes #I4M172 #248 #I4L3DN
=> [I4L3DN] [I4M172] [248] Fix Read Issue for Struct Data Column

presto-orc/src/test/java/io/prestosql/orc/OrcTester.java
=> [246] Local of Known Non Null

presto-memory/src/main/java/io/prestosql/plugin/memory/data/MemoryTableManager.java
=> OpenStream and return value ignored fixed

presto-hive/src/main/java/io/prestosql/plugin/hive/orc/OrcPageSourceFactory.java, presto-hive/src/test/java/io/prestosql/plugin/hive/TestHiveIntegrationSmokeTest.java
=> [I4NBP3] [260] Single Column Read or Update Issue Fix

presto-main/src/test/java/io/prestosql/operator/spiller/BenchmarkBinaryFileSpiller.java
/kind task
Fixed microbench testcase to include various parameters for spillers (directSerde,compression,encryption,preFetch etc)
**Sample output**
```
Benchmark                                  (compressionEnabled)  (directSerdeEnabled)  (encryptionEnabled)  (pagesCount)  (rowsPerPage)  (spillPrefetchReadPages)   Mode  Cnt    Score    Error  Units
BenchmarkBinaryFileSpiller.writeReadSpill                 false                 false                false            10          10000                         1  thrpt   10  137.072 ±  3.129  ops/s
BenchmarkBinaryFileSpiller.writeReadSpill                 false                 false                false            10          10000                        25  thrpt   10  134.595 ±  1.658  ops/s
BenchmarkBinaryFileSpiller.writeReadSpill …
```
=> Spiller microbenchmark enhancements additional params

presto-main/src/main/java/io/prestosql/operator/OrderByOperator.java, presto-main/src/main/java/io/prestosql/operator/TableScanOperator.java, presto-main/src/main/java/io/prestosql/operator/WindowOperator.java, presto-main/src/main/java/io/prestosql/operator/WorkProcessorSourceOperatorAdapter.java, presto-main/src/main/java/io/prestosql/operator/aggregation/builder/SpillableHashAggregationBuilder.java
=> [264]: Spill to disk log

presto-spi/src/main/java/io/prestosql/spi/block/VariableWidthBlockEncoding.java
=> Fix Kryo Serialization Issue for empty VariableWidthBlock

presto-hive/src/main/java/io/prestosql/plugin/hive/OrcFileWriterFactory.java, presto-main/src/main/java/io/prestosql/execution/SqlQueryExecution.java, presto-main/src/main/java/io/prestosql/execution/scheduler/NodeScheduler.java, presto-main/src/main/java/io/prestosql/execution/scheduler/SqlQueryScheduler.java, presto-main/src/main/java/io/prestosql/failuredetector/FailureDetector.java, presto-main/src/main/java/io/prestosql/failuredetector/HeartbeatFailureDetector.java, presto-main/src/main/java/io/prestosql/metadata/DiscoveryNodeManager.java, presto-main/src/main/java/io/prestosql/metadata/InMemoryNodeManager.java, presto-main/src/main/java/io/prestosql/metadata/InternalNodeManager.java
=> [I4Y3TQ] Fix Polling Workers Sync Issue For Resume Flow

hetu-docs/en/admin/properties.md, presto-main/src/main/java/io/prestosql/snapshot/QuerySnapshotManager.java
=> [I4ZB03] Fix Resetting Retry Count on Restore Success

presto-main/src/main/java/io/prestosql/snapshot/QuerySnapshotManager.java
bug
Added null check to avoid crash in unusual flows
Fixes https://gitee.com/openlookeng/hetu-core/issues/I504PV
=> Added null check to avoid crash in unusual flows

presto-main/src/main/java/io/prestosql/operator/HttpPageBufferClient.java, presto-main/src/test/java/io/prestosql/operator/TestHttpPageBufferClient.java
/kind bug 
handle resumable exception in case of HTTP request when raised directly
Fixes #I4Y3TQ
=> [I4Y3TQ] handle exception in httpRequest for resumable failure

presto-main/src/main/java/io/prestosql/execution/SqlTaskExecution.java, presto-main/src/main/java/io/prestosql/execution/executor/TaskExecutor.java, presto-main/src/main/java/io/prestosql/execution/executor/TaskHandle.java, presto-main/src/main/java/io/prestosql/server/TaskResource.java, presto-main/src/main/java/io/prestosql/server/remotetask/HttpRemoteTask.java, presto-main/src/main/resources/webapp/src/components/QueryDetail.jsx, presto-main/src/main/resources/webapp/src/components/QueryHeader.jsx, presto-main/src/main/resources/webapp/src/components/QueryMonitor.jsx, presto-main/src/main/resources/webapp/src/newUtils.js, presto-main/src/main/resources/webapp/src/utils.js, presto-main/src/main/resources/webapp/src/yarn.lock
/kind bug
* Adds Webui changes for listing Suspended queries.
* Added single click freeze button for suspend/resume buttons.
* Added Query list filter for Suspended queries
* Added Task list filter for Suspended tasks
* State change recorded in Remote task to prevent duplicates request execution;
* Changed the request type to Delete instead of Get.
Fixes #I59M5L
=> [I59M5L] Suspend-Resume hang fix

presto-main/src/main/java/io/prestosql/memory/QueryContext.java, presto-main/src/test/java/io/prestosql/snapshot/TestQueryRecoveryManager.java
bug 
Fixing NullPointerexception issue while recovering from snapshot in HA mode, and random unit test failure in CI env 
Fixes #I59PLF
=> Fixing issue while recovering from snapshot in HA mode

presto-main/src/main/java/io/prestosql/operator/HashBuilderOperator.java
=> [I5CM66] Fix Not Serializable Exception for SpilledBlooms

presto-main/src/test/java/io/prestosql/execution/scheduler/TestFixedCountNodeAllocator.java, presto-main/src/test/java/io/prestosql/execution/scheduler/TestTaskDescriptorStorage.java
=> Add UT's for FixedCountNodeAllocator and TaskDescriptorStorage

presto-main/src/test/java/io/prestosql/exchange/AbstractTestExchangeManager.java, presto-main/src/test/java/io/prestosql/exchange/LocalFileSystemExchangeManagerTest.java, presto-main/src/test/java/io/prestosql/exchange/TestFileSystemExchangeConfig.java, presto-main/src/test/java/io/prestosql/exchange/TestFileSystemExchangeSource.java
task
Added new UT test cases
Fixes: #411
=> Added new unit test cases for file system exchange

presto-main/src/test/java/io/prestosql/execution/TestQueryPreparer.java, presto-main/src/test/java/io/prestosql/sql/planner/optimizations/TestAddExchangesPlans.java, presto-orc/src/test/java/io/prestosql/orc/TestDynamicFilterOrcPredicate.java, presto-spi/src/test/java/io/prestosql/spi/TestPage.java
/kind task 
add UT cases for required scenarios
Fixes #413
=> unit test cases

presto-main/src/test/java/io/prestosql/block/TestDictionaryBlock.java, presto-main/src/test/java/io/prestosql/execution/warnings/TestLogicalPlanner.java, presto-main/src/test/java/io/prestosql/sql/query/TestUnnest.java, presto-spi/src/test/java/io/prestosql/spi/cube/TestCubeUpdateMetadata.java
/kind task
add UT cases for required scenarios
Fixes #415
=> Added UT testcase
